<?php

namespace Test\DiTesto;

use LazyEight\DiTesto\Exceptions\IOException;
use LazyEight\DiTesto\FileSystem\FileSystemHandler;
use LazyEight\DiTesto\Line;
use LazyEight\DiTesto\TextFile;
use LazyEight\DiTesto\FileWriter;
use PHPUnit\Framework\TestCase;

class FileWriterTest extends TestCase
{
    /**
     * @var string
     */
    protected $file = './tests/files/urls.txt';

    /**
     * @var string
     */
    protected $path = './tests/files';

    /**
     * @var string
     */
    protected $newFilename = 'newFilename.txt';

    /**
     * @var string
     */
    protected $testLine = 'THIS IS A TEST LINE';

    /**
     * @covers \LazyEight\DiTesto\FileWriter::writeFile
     * @covers \LazyEight\DiTesto\FileSystem\FileSystemHandler::exists
     * @covers \LazyEight\DiTesto\FileSystem\FileSystemHandler::isWritable
     * @covers \LazyEight\DiTesto\FileSystem\FileSystemHandler::write
     * @uses \LazyEight\DiTesto\FileWriter
     */
    public function testWriteFile()
    {
        $newFilename = $this->path . '/' . $this->newFilename;
        $textFile = new TextFile($newFilename);
        $textFile[] = new Line($this->testLine);

        (new FileWriter())->writeFile($textFile, new FileSystemHandler());
        $this->assertTrue((new FileSystemHandler())->exists($textFile->getPath()));
    }

    /**
     * @covers \LazyEight\DiTesto\FileWriter::writeFile
     * @covers \LazyEight\DiTesto\FileSystem\FileSystemHandler::exists
     * @covers \LazyEight\DiTesto\FileSystem\FileSystemHandler::isWritable
     * @covers \LazyEight\DiTesto\FileSystem\FileSystemHandler::write
     * @uses \LazyEight\DiTesto\FileWriter
     * @expectException IOException
     */
    public function testCantWriteFile()
    {
        $path = $this->path . '/' . 'newPath';
        mkdir($path);
        chmod($path, 0555);

        $newFilename = $path . '/' . $this->newFilename;
        $textFile = new TextFile($newFilename);
        $textFile[] = new Line($this->testLine);

        $this->expectException(IOException::class);
        (new FileWriter())->writeFile($textFile, new FileSystemHandler());
    }

    /**
     * @inheritDoc
     */
    public static function tearDownAfterClass()
    {
        $file = './tests/files/newFilename.txt';
        $newFilePath = './tests/files/newPath';

        if (file_exists($file)) {
            unlink($file);
        }

        if (file_exists($newFilePath)) {
            rmdir($newFilePath);
        }

        parent::tearDownAfterClass(); // TODO: Change the autogenerated stub
    }
}
